name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hello! Making an issue? Remember to add a lot of detail, as much as you can.'
        pr-message: 'No pull request message; submit one so we can have one!'
